x = linspace(0,100,200);
A = 3;
k = 3500;
m = 50;
f = 0;
omega = sqrt(k/m);
b = 18;
gamma = b/m;
sz = -1 * gamma / 2;
fd= f;
omegad = sqrt(omega^2-sz^2);
figure;
plot(x, A.*exp(x*sz).*cos((omegad*x+fd)));
hold on;
omega = linspace(0,100,200);
omegad = linspace(0,100,200);
figure;
plot(omegad,abs(A*exp(sz*omega)),".b" ,omega , A, ".r");
hold on;
figure;
plot(omega, f+atan2(0,A*exp(sz*omega)), ".y");
hold on;
Add = (A*exp(sz*omega));
niq = complex(Add, zeros(size(Add)));
figure;
plot(real(niq),imag(niq), "*");
hold off;