x = linspace(0,20,500);
f0 = 0;
f = f0+0;
A = 2;
k1 = 350;
m1 = 10;
k = 35;
m = 10;
omega = sqrt(k/m);
omegaf = sqrt(k1/m1);
ff = 500;
B = abs(((ff/m))./(omega.^2 - omegaf.^2));
figure;
plot(x, A .* cos(omega*x+f0) + B .* cos(omegaf*x+f));
hold on;
figure;
plot(x, B .* cos(omegaf*x+f));
hold on;
omega = linspace(0,14,500);
figure;
plot(omega,abs(((ff/m))./(omega.^2 - omegaf.^2)));
hold on;
figure;
plot(omega, f0+atan2(0,((ff/m))./(omega.^2 - omegaf.^2)));
hold on;
figure;
Aff = abs(((ff/m))./(omega.^2 - omegaf.^2));
niq = complex(Aff,zeros(size(Aff)));
plot(real(niq), imag(niq), '*', 'LineWidth', 1.5);
hold off;

