x = linspace(0,200,800);
A = 3;
k = 4000;
m = 60;
f = 0;
omega = sqrt(k/m);
b = 5;
gamma = b/m;
szig = -1*gamma/2;
k1 = 5000;
m1 = 20;
fd= f;
ff = 250;
omegaf = sqrt(k1/m1);
omegad = sqrt(omega^2-szig^2);
B = (ff/m)/(omega^2-omegaf^2);
figure;
plot(x, A.*exp(x*szig).*cos((omegad*x+fd))+B.*cos((omegaf*x+ff)));
omegaf = linspace(0,15,800);
hold on;
figure;
plot(omegaf,(ff/m).*(1./sqrt((omega^2-omegaf.^2).^2+(gamma.*omegaf).^2)));
hold on;
figure;
plot(omegaf,f+atan2(-1*(gamma.*omegaf), (omega^2-omegaf.^2)));
hold on;
figure;
AB = (ff/m).*(1./sqrt((omega^2-omegaf.^2).^2+(gamma.*omegaf).^2));
nyp = complex(B,atan2(-1*(gamma.*omegaf), (omega^2-omegaf.^2)));
plot(real(nyp), imag(nyp), "*");